### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Minhe173** [1x6/roblox-always-online#1]
Whats this?!?!
![image](https://user-images.githubusercontent.com/88653001/163142505-6315c3af-e41e-4a17-bb19-5168aeb49708.png)

**Comment by Minhe173** [comment]
@1x6

**Comment by 1x6** [comment]
google it lol

did you put in the right cookie?

**Comment by Minhe173** [comment]
ye

**Comment by Minhe173** [comment]
oke!

**Comment by Minhe173** [comment]
@1x6

**Comment by 1x6** [comment]
works just fine for me..

can u give any more info?
try running on ur local pc or use a diff cookie

**Comment by Minhe173** [comment]
oke

**Comment by Minhe173** [comment]
but i need it 24/7

**Comment by Minhe173** [comment]
so im using replit

**Comment by Minhe173** [comment]
@1x6

**Comment by Minhe173** [comment]
ok

**Comment by Minhe173** [comment]
can u send me railway website @1x6

**Comment by 1x6** [comment]
https://railway.app

**Comment by Minhe173** [comment]
![image](https://user-images.githubusercontent.com/88653001/166631256-1319d88c-2bcb-41f2-aa4d-dcc6f4cd09d9.png)
ehh

**Comment by Minhe173** [comment]
@1x6

**Comment by 1x6** [comment]
you need to configure it

**Comment by Minhe173** [comment]
how? send me ss

**Comment by Minhe173** [comment]
@1x6

**Comment by 1x6** [comment]
https://docs.railway.app/deploy/python
